#include "src/utils/utils.hpp"

/**
 * \brief The handshaking protocol for client and server mutual identification
 *
The handshaking protocol relies on exchanging keys over a pre-existing channel consisting of two
pipes. The server-to-client handshake pipe conveys a key generated by the server to the client.
The client-to-server handshake pipe conveys a key generated by the client to the server. The
server-to-client handhake pipe is also used to provide the name of the server socket, so that the
client can connect to it.

The procedure is as follows

1. The server generates a random handshake_key and sends it to the client through the
   server-to-client handshake pipe

2. The client generates a random handshake_key and sends it to the client through the
   client-to-server handshake pipe

3. The server sends the socket name through the server-to-client handshake pipe

4. The client connects to the server

5. The server sends back the key it received from the client-to-server pipe, over the socket

6. The client compares the key it received from the socket, to the key generated in step (2)
   If not equal, the client disconnects, otherwise

7. The client responds with the key it was given in step (1)

8. If the key received from the client in the response is not equal to the key generated in
   step(1), the server closes the connection, otherwise, the handshake procedure has been
   completed.
 */
namespace prog::handshaking_protocol
{
	using server_socket_name = std::array<char, prog::utils::num_chars_16_bytes>;
	using handshake_key = std::array<std::byte, 16>;
}