@startuml
left to right direction
component host_application {
	component client{
		portin log_in
		portin ctl_in
		portout ctl_out
		portout decoded_log_msg
	}

	queue log_messages{
		portin log_messages_in
		portout log_messages_out
	}

	component ui {
		portin log
		portin user_events
	}
}

component client_application {
	portin stdin
	portout stdout
	portout stderr
	portin data_in
	portout data_out
}

ctl_out -up-> stdin: <<pipe>>
stdout -up-> ctl_in: <<pipe>>
stderr -up-> log_in: <<pipe>>
decoded_log_msg -> log_messages_in
log_messages_out -right-> log
@enduml